### ISSUE TITLE
Impossible to assert takeLeading effect in TypeScript

### ISSUE THREAD

**Issue by wh1t3cAt1k** [jfairbank/redux-saga-test-plan#264]
Version: 4.0.0 beta 2.

I see `takeLeading` in JS sources but it is nowhere to be found in TypeScript typings.

As a temporary workaround, I would be glad to extend library typings with some custom ones, but not without guidance.

Any help is appreciated.

**Comment by jp928** [comment]
resolved in #265 .
Please reinstall the library.

**Comment by wh1t3cAt1k** [comment]
It's still not published in `npm`, apologies, any plans to publish it as the new beta?
